version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "127.0.0.1:16686:16686"
      - "127.0.0.1:14268:14268"
      - "127.0.0.1:14250:14250"
  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "127.0.0.1:13133:13133" # Health_check extension
      - "127.0.0.1:4317:4317"   # OTLP gRPC receiver
      - "127.0.0.1:55680:55680" # OTLP gRPC receiver alternative port
    depends_on:
      - jaeger-all-in-one
